package com.bank.enums;

public enum Errors {
	INVALID_USER,
	INVALID_SESSION,
	WRONG_PASSWORD,
	NO_ACCOUNT_FOUND,
	WRONG_USER_ID,
	WRONG_ACCOUNT_NUMBER,
	INVALID_CUSTOMER,
	INVALID_EMPLOYEE,
	INVALID_BRANCH
}